name: "✨ Feature Request"
description: "Suggest a new feature"
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Describe the feature"
      description: "What would you like to see?"
      placeholder: "Support for comparing 3+ test runs..."
    validations:
      required: true
  
  - type: textarea
    id: usecase
    attributes:
      label: "Use case"
      description: "Why do you need this?"
      value: |
        Use case: 
        Problem it solves:
        Impact:
    validations:
      required: true
  
  - type: textarea
    id: example
    attributes:
      label: "Example usage"
      description: "How would users use this?"
      placeholder: "deltalinse baseline.xml current.xml --trend"
  
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternative approaches"
      description: "What other ways could this work?"
  
  - type: textarea
    id: additional
    attributes:
      label: "Additional context"
      description: "Mockups, links, references?"
