name: "❓ Question / Discussion"
description: "Ask a question about DeltaLinse"
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: "Your question"
      description: "What do you want to know?"
      placeholder: "How do I use DeltaLinse with..."
    validations:
      required: true
  
  - type: textarea
    id: context
    attributes:
      label: "Context"
      description: "Tell us about your use case"
      placeholder: "I'm trying to..."
  
  - type: input
    id: node_version
    attributes:
      label: "Node.js version"
      placeholder: "20.10.0"
  
  - type: textarea
    id: additional
    attributes:
      label: "Additional details"
      description: "Anything else we should know?"
